services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      SECRET_KEY_BASE: nfCw6Eh6F5u9KBZlyTymQ9GsW/Wckyvn+FGCpuhiXDErEnH6klbvEb8jw9d1zccB
      PHX_HOST: localhost
      PORT: 4000
